# -*- coding: utf-8 -*-
"""Cod_acoes_nacionais

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MUb5bYVVpOIYnM33UWPP1La7tRpUKwud
"""

import yfinance as yf
import pandas as pd
from datetime import datetime, timedelta
import pytz
import smtplib
from email.message import EmailMessage

# Lista de tickers
tickers = ['BBSE3.SA','BBAS3.SA','TAEE4.SA','ITSA4.SA']

# Timezone de São Paulo
tz = pytz.timezone("America/Sao_Paulo")

# Datas de referência com timezone
hoje = datetime.now(tz)
um_ano_atras = tz.localize(datetime(hoje.year - 1, hoje.month, hoje.day))
inicio_ano_passado = tz.localize(datetime(hoje.year - 1, 1, 1))
fim_ano_passado = tz.localize(datetime(hoje.year - 1, 12, 31))

# Coletar dados
dados = []

for ticker in tickers:
    acao = yf.Ticker(ticker)

    # Histórico de preços
    historico = acao.history(period='7d')
    fechamento_ontem = historico['Close'].iloc[-2] if len(historico) >= 2 else None
    preco_atual = acao.info.get('regularMarketPrice', None)

    # Dividendos
    dividendos = acao.dividends
    dividendos.index = dividendos.index.tz_convert("America/Sao_Paulo")  # garantir timezone compatível

    dividendos_12m = dividendos[dividendos.index >= um_ano_atras].sum()
    dividendos_ano_passado = dividendos[(dividendos.index >= inicio_ano_passado) & (dividendos.index <= fim_ano_passado)].sum()

    # Dividend Yield
    dy_12m = (dividendos_12m / preco_atual * 100) if preco_atual else None
    dy_ano_passado = (dividendos_ano_passado / preco_atual * 100) if preco_atual else None

    dados.append({
        'Ticker': ticker,
        'Fechamento Ontem': round(fechamento_ontem, 2) if fechamento_ontem else 'N/A',
        'Preço Atual': round(preco_atual, 2) if preco_atual else 'N/A',
        'Dividendos 12M': round(dividendos_12m, 2),
        'Dividendos Ano Passado': round(dividendos_ano_passado, 2),
        'DY 12M (%)': round(dy_12m, 2) if dy_12m else 'N/A',
        'DY Ano Passado (%)': round(dy_ano_passado, 2) if dy_ano_passado else 'N/A'
    })

# Exibir os dados em um DataFrame
df = pd.DataFrame(dados)

# Enviar por e-mail
msg = EmailMessage()
msg['Subject'] = 'Relatório Diário de Ações com Dividendos'
msg['From'] = 'leosarkisj@gmail.com'
msg['To'] = ['leosarkisj@gmail.com','andreluisribeirogarcia@gmail.com']


# Gerar tabela em HTML
tabela_html = df.to_html(index=False, border=1)

# Corpo do e-mail em HTML
msg.set_content("Este e-mail contém um relatório em HTML. Por favor, visualize em um cliente de e-mail compatível.")
msg.add_alternative(f"""
<html>
  <body>
    <p>Olá,<br><br>
       Segue abaixo o relatório diário das ações:<br><br>
       {tabela_html}
       <br><br>
       Atenciosamente,<br>
       Seu Agente Financeiro
    </p>
  </body>
</html>
""", subtype='html')

with smtplib.SMTP_SSL('smtp.gmail.com', 465) as smtp:
    smtp.login('leosarkisj@gmail.com', 'arqb mwkn vzht vgti')
    smtp.send_message(msg)

